// t-SNE filename mapping: {promptIdx}-{group} -> filename
export const TSNE_FILENAME_MAPPING: Record<string, string> = {
  // Prompt 0: "Hi there! I can grant you one big wish..."
  '0-Jewish': 'tsne_plot__Jewish__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-Christian': 'tsne_plot__Christian__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-Muslim': 'tsne_plot__Muslim__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-Black': 'tsne_plot__Black__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-White': 'tsne_plot__White__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-Hispanic': 'tsne_plot__Hispanic__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-Buddhist': 'tsne_plot__Buddhist__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-Hindu': 'tsne_plot__Hindu__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-Asian': 'tsne_plot__Asian__Hi_there_I_can_grant_you_one_big_wish_bu.html',
  '0-Arab': 'tsne_plot__Arab__Hi_there_I_can_grant_you_one_big_wish_bu.html',

  // Prompt 1: "Hi there! I can bring about any future..."
  '1-Jewish': 'tsne_plot__Jewish__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-Christian': 'tsne_plot__Christian__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-Muslim': 'tsne_plot__Muslim__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-Black': 'tsne_plot__Black__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-White': 'tsne_plot__White__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-Hispanic': 'tsne_plot__Hispanic__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-Buddhist': 'tsne_plot__Buddhist__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-Hindu': 'tsne_plot__Hindu__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-Asian': 'tsne_plot__Asian__Hi_there_I_can_bring_about_any_future_bu.html',
  '1-Arab': 'tsne_plot__Arab__Hi_there_I_can_bring_about_any_future_bu.html',

  // Prompt 2: "Hi there! I can grant you whatever you want..."
  '2-Jewish': 'tsne_plot__Jewish__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-Christian': 'tsne_plot__Christian__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-Muslim': 'tsne_plot__Muslim__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-Black': 'tsne_plot__Black__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-White': 'tsne_plot__White__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-Hispanic': 'tsne_plot__Hispanic__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-Buddhist': 'tsne_plot__Buddhist__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-Hindu': 'tsne_plot__Hindu__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-Asian': 'tsne_plot__Asian__Hi_there_I_can_grant_you_whatever_you_wa.html',
  '2-Arab': 'tsne_plot__Arab__Hi_there_I_can_grant_you_whatever_you_wa.html',

  // Prompt 3: "Hi there! I can make one event happen..."
  '3-Jewish': 'tsne_plot__Jewish__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-Christian': 'tsne_plot__Christian__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-Muslim': 'tsne_plot__Muslim__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-Black': 'tsne_plot__Black__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-White': 'tsne_plot__White__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-Hispanic': 'tsne_plot__Hispanic__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-Buddhist': 'tsne_plot__Buddhist__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-Hindu': 'tsne_plot__Hindu__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-Asian': 'tsne_plot__Asian__Hi_there_I_can_make_one_event_happen_inv.html',
  '3-Arab': 'tsne_plot__Arab__Hi_there_I_can_make_one_event_happen_inv.html',

  // Prompt 4: "Hi there! I can make one specific change..."
  '4-Jewish': 'tsne_plot__Jewish__Hi_there_I_can_make_one_specific_change_.html',
  '4-Christian': 'tsne_plot__Christian__Hi_there_I_can_make_one_specific_change_.html',
  '4-Muslim': 'tsne_plot__Muslim__Hi_there_I_can_make_one_specific_change_.html',
  '4-Black': 'tsne_plot__Black__Hi_there_I_can_make_one_specific_change_.html',
  '4-White': 'tsne_plot__White__Hi_there_I_can_make_one_specific_change_.html',
  '4-Hispanic': 'tsne_plot__Hispanic__Hi_there_I_can_make_one_specific_change_.html',
  '4-Buddhist': 'tsne_plot__Buddhist__Hi_there_I_can_make_one_specific_change_.html',
  '4-Hindu': 'tsne_plot__Hindu__Hi_there_I_can_make_one_specific_change_.html',
  '4-Asian': 'tsne_plot__Asian__Hi_there_I_can_make_one_specific_change_.html',
  '4-Arab': 'tsne_plot__Arab__Hi_there_I_can_make_one_specific_change_.html',

  // Prompt 5: "Hi there! I can set up one scenario..."
  '5-Jewish': 'tsne_plot__Jewish__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-Christian': 'tsne_plot__Christian__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-Muslim': 'tsne_plot__Muslim__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-Black': 'tsne_plot__Black__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-White': 'tsne_plot__White__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-Hispanic': 'tsne_plot__Hispanic__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-Buddhist': 'tsne_plot__Buddhist__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-Hindu': 'tsne_plot__Hindu__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-Asian': 'tsne_plot__Asian__Hi_there_I_can_set_up_one_scenario_invol.html',
  '5-Arab': 'tsne_plot__Arab__Hi_there_I_can_set_up_one_scenario_invol.html',

  // Prompt 6: "Hi there! I can influence one aspect..."
  '6-Jewish': 'tsne_plot__Jewish__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-Christian': 'tsne_plot__Christian__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-Muslim': 'tsne_plot__Muslim__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-Black': 'tsne_plot__Black__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-White': 'tsne_plot__White__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-Hispanic': 'tsne_plot__Hispanic__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-Buddhist': 'tsne_plot__Buddhist__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-Hindu': 'tsne_plot__Hindu__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-Asian': 'tsne_plot__Asian__Hi_there_I_can_influence_one_aspect_invo.html',
  '6-Arab': 'tsne_plot__Arab__Hi_there_I_can_influence_one_aspect_invo.html',

  // Prompt 7: "Hi there! I can create one opportunity..."
  '7-Jewish': 'tsne_plot__Jewish__Hi_there_I_can_create_one_opportunity_in.html',
  '7-Christian': 'tsne_plot__Christian__Hi_there_I_can_create_one_opportunity_in.html',
  '7-Muslim': 'tsne_plot__Muslim__Hi_there_I_can_create_one_opportunity_in.html',
  '7-Black': 'tsne_plot__Black__Hi_there_I_can_create_one_opportunity_in.html',
  '7-White': 'tsne_plot__White__Hi_there_I_can_create_one_opportunity_in.html',
  '7-Hispanic': 'tsne_plot__Hispanic__Hi_there_I_can_create_one_opportunity_in.html',
  '7-Buddhist': 'tsne_plot__Buddhist__Hi_there_I_can_create_one_opportunity_in.html',
  '7-Hindu': 'tsne_plot__Hindu__Hi_there_I_can_create_one_opportunity_in.html',
  '7-Asian': 'tsne_plot__Asian__Hi_there_I_can_create_one_opportunity_in.html',
  '7-Arab': 'tsne_plot__Arab__Hi_there_I_can_create_one_opportunity_in.html',
};
